const actionTypes = {

  SET_LANGUAGE: "SET_LANGUAGE",

  //modify section
  SET_SECTION: "SET_SECTION",

  //modify filters
  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",
  SET_FILTERS_ADVENTURER_WEAPON_TYPE: "SET_FILTERS_ADVENTURER_WEAPON_TYPE",
  SET_FILTERS_WEAPON_TYPE: "SET_FILTERS_WEAPON_TYPE",
  SET_FILTERS_DRAGON_ELEMENT: "SET_FILTERS_DRAGON_ELEMENT",

  //modify stats
  SELECT_STATS: "SELECT_STATS",
  RESET_STATS: "RESET_STATS",
  UPDATE_STATS: "UPDATE_STATS",

  //modify halidom
  RESET_HALIDOM: "RESET_HALIDOM",
  SELECT_HALIDOM: "SELECT_HALIDOM",
  MAX_HALIDOM: "MAX_HALIDOM",
  DEFAULT_HALIDOM: "DEFAULT_HALIDOM",
  UPDATE_HALIDOM: "UPDATE_HALIDOM",

  RESET_DETAILS: "RESET_DETAILS",
  UPDATE_DETAILS: "UPDATE_DETAILS",
}

export default actionTypes;