const actionTypes = {
  //modify details button
  TOGGLE_DETAILS: "TOGGLE_DETAILS",
  HIDE_DETAILS: "HIDE_DETAILS",
  //modify section
  SET_SECTION: "SET_SECTION",

  //modify filters
  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",
  SET_FILTERS_ADVENTURER_TYPE: "SET_FILTERS_ADVENTURER_TYPE",
  SET_FILTERS_WEAPON_TYPE: "SET_FILTERS_WEAPON_TYPE",
  SET_FILTERS_DRAGON_ELEMENT: "SET_FILTERS_DRAGON_ELEMENT",

  //modify status
  SELECT_STATUS: "SELECT_STATUS",
  REMOVE_STATUS: "REMOVE_STATUS",
  UPDATE_STATUS: "UPDATE_STATUS",

  UPDATE_STATUS_LEVEL: "UPDATE_STATUS_LEVEL",
  UPDATE_STATUS_UNBIND: "UPDATE_STATUS_UNBIND",
  UPDATE_STATUS_ADVENTURER_RARITY_MANA: "UPDATE_STATUS_ADVENTURER_RARITY_MANA",

  //calc status
  UPDATE_DETAILS: "UPDATE_DETAILS",

}

export default actionTypes;