const actionTypes = {

  //modify section
  SET_SECTION: "SET_SECTION",

  //modify filters
  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",
  SET_FILTERS_ADVENTURER_WEAPON_TYPE: "SET_FILTERS_ADVENTURER_WEAPON_TYPE",
  SET_FILTERS_WEAPON_TYPE: "SET_FILTERS_WEAPON_TYPE",
  SET_FILTERS_DRAGON_ELEMENT: "SET_FILTERS_DRAGON_ELEMENT",

  //modify status
  SELECT_STATS: "SELECT_STATS",
  REMOVE_STATS: "REMOVE_STATS",
  UPDATE_STATS: "UPDATE_STATS",
  UPDATE_STATS_LEVEL: "UPDATE_STATS_LEVEL",
  UPDATE_STATS_UNBIND: "UPDATE_STATS_UNBIND",
  UPDATE_STATS_ADVENTURER_RARITY_MANA: "UPDATE_STATS_ADVENTURER_RARITY_MANA",

  //calc status
  UPDATE_DETAILS: "UPDATE_DETAILS",

}

export default actionTypes;