const actionTypes = {

  SET_LANGUAGE: "SET_LANGUAGE",

  //modify section
  SET_SECTION: "SET_SECTION",

  //modify filters
  SET_FILTERS: "SET_FILTERS",
  RESET_FILTERS: "RESET_FILTERS",
  SET_FILTERS_ADVENTURER_WEAPON_TYPE: "SET_FILTERS_ADVENTURER_WEAPON_TYPE",
  SET_FILTERS_WEAPON_TYPE: "SET_FILTERS_WEAPON_TYPE",
  SET_FILTERS_DRAGON_ELEMENT: "SET_FILTERS_DRAGON_ELEMENT",

  //modify status
  SELECT_STATS: "SELECT_STATS",
  UPDATE_STATS_VALUE: "UPDATE_STATS_VALUE",

  //modify halidom
  UPDATE_HALIDOM_VALUE: "UPDATE_HALIDOM_VALUE",

  UPDATE_DETAILS: "UPDATE_DETAILS",
  UPDATE_DETAILS_ADVENTURER: "UPDATE_DETAILS_ADVENTURER",
  UPDATE_DETAILS_WEAPON: "UPDATE_DETAILS_WEAPON",
  UPDATE_DETAILS_WYRMPRINT: "UPDATE_DETAILS_WYRMPRINT",
  UPDATE_DETAILS_DRAGON: "UPDATE_DETAILS_DRAGON",
  UPDATE_DETAILS_HALIDOM: "UPDATE_DETAILS_HALIDOM",
}

export default actionTypes;