const actionTypes = {

  SELECT_LANGUAGE: "SELECT_LANGUAGE",
  //modify section
  SELECT_SECTION: "SELECT_SECTION",

  //modify filters
  RESET_FILTERS: "RESET_FILTERS",
  SELECT_FILTERS: "SELECT_FILTERS",
  NARROW_DOWN_FILTERS: "NARROW_DOWN_FILTERS",

  //modify stats
  RESET_STATS: "RESET_STATS",
  SELECT_STATS: "SELECT_STATS",
  UPDATE_STATS: "UPDATE_STATS",

  //modify halidom
  RESET_HALIDOM: "RESET_HALIDOM",
  SELECT_HALIDOM: "SELECT_HALIDOM",
  UPDATE_HALIDOM: "UPDATE_HALIDOM",
  DEFAULT_HALIDOM: "DEFAULT_HALIDOM",
  MAX_HALIDOM: "MAX_HALIDOM",

  RESET_DETAILS: "RESET_DETAILS",
  UPDATE_DETAILS: "UPDATE_DETAILS",
}

export default actionTypes;