const actionTypes = {
  RESET_OPTIONS: 'RESET_OPTIONS',
  LIGHT_OPTION: 'LIGHT_OPTION',
  SELECT_OPTION: 'SELECT_OPTION',
  SELECT_FOCUS: 'SELECT_FOCUS',
  SELECT_ITEM: 'SELECT_ITEM',
};

export default actionTypes;
