const actionTypes = {

  RESET: "RESET",

  SELECT_COL: "SELECT_COL",
  SELECT_FOCUS: "SELECT_FOCUS",
  //filters
  SELECT_FILTERS: "SELECT_FILTERS",
  NARROW_FILTERS: "NARROW_FILTERS",

  //stats
  SYNC_STATS: "SYNC_STATS",
  SELECT_STATS: "SELECT_STATS",
  UPDATE_STATS: "UPDATE_STATS",

  //halidom
  RESET_FIELD: "RESET_FIELD",
  UPDATE_HALIDOM: "UPDATE_HALIDOM",

  //details
  UPDATE_DETAILS: "UPDATE_DETAILS",
}

export default actionTypes;