const actionTypes = {
  RESET: 'RESET',
  RESET_FILTERS: 'RESET_FILTERS',

  SELECT_FILTERS: 'SELECT_FILTERS',
  SELECT_PANEL: 'SELECT_PANEL',
  SELECT_FOCUS: 'SELECT_FOCUS',
  //stats
  SYNC_STATS: 'SYNC_STATS',
  SELECT_STATS: 'SELECT_STATS',
  UPDATE_STATS: 'UPDATE_STATS',
  //halidom
  LOAD_HALIDOM: 'LOAD_HALIDOM',
  UPDATE_HALIDOM: 'UPDATE_HALIDOM',
  //details
  UPDATE_DETAILS: 'UPDATE_DETAILS',
};

export default actionTypes;
