export default {
  stats: { en: "Stats", zh: "属性", ja: "状態" },
  dungeon: { en: "Dungeon", zh: "副本", ja: "ダンジョン" },
  adventurer: { en: "Adventurer", zh: "角色", ja: "キャラ" },
  weapon: { en: "Weapon", zh: "武器", ja: "武器" },
  wyrmprint: { en: "Wyrmprint", zh: "龙辉护符", ja: "竜輝の護符" },
  wyrmprint1: { en: "Wyrmprint", zh: "龙辉护符", ja: "竜輝の護符" },
  wyrmprint2: { en: "Wyrmprint", zh: "龙辉护符", ja: "竜輝の護符" },
  dragon: { en: "Dragon", zh: "龙", ja: "ドラゴン" },
  ability: { en: "Ability", zh: "能力", ja: "アビリティ" },
  halidom: { en: "Halidom", zh: "圣城", ja: "聖城" },
  total: { en: "Total", zh: "合计", ja: "合計" },
  HP: { en: "HP", zh: "HP", ja: "HP" },
  STR: { en: "STR", zh: "攻击力", ja: "攻撃力" },
  might: { en: "Might", zh: "战力", ja: "戦力" },
  //UI
  reset: { en: "Reset", zh: "重置", ja: "リセット" },
  default: { en: "Default", zh: "默认值", ja: "デフォルト" },
  max: { en: "MAX", zh: "最大值", ja: "最大値" },
  setting: { en: "Setting", zh: "设置", ja: "設定" },

  //stats
  name: { en: "Name", zh: "名称", ja: "名称" },
  level: { en: "Level", zh: "等级", ja: "レベル" },
  rarity: { en: "Rarity", zh: "稀有度", ja: "レアリティ" },
  curRarity: { en: "Rarity", zh: "稀有度", ja: "レアリティ" },
  ex: { en: "CoAbility", zh: "EX", ja: "EXアビリティ" },
  mana: { en: "Mana Circle", zh: "魔法圆环", ja: "マナサークル" },
  type: { en: "Type", zh: "武器种类", ja: "武器種" },
  element: { en: "Element", zh: "属性", ja: "属性" },
  tier: { en: "Tier", zh: "阶段", ja: "段階" },
  unbind: { en: "Unbind", zh: "上限解锁", ja: "上限解放" },
  bond: { en: "Bond", zh: "信赖度", ja: "Bond" },
  //weaponType
  Sword: { en: "Sword", zh: "剑", ja: "剣" },
  Blade: { en: "Blade", zh: "刀", ja: "刀" },
  Dagger: { en: "Dagger", zh: "短剑", ja: "短剣" },
  Axe: { en: "Axe", zh: "斧", ja: "斧" },
  Lance: { en: "Lance", zh: "枪", ja: "槍" },
  Bow: { en: "Bow", zh: "弓", ja: "弓" },
  Wand: { en: "Wand", zh: "魔杖", ja: "ロッド" },
  Staff: { en: "Staff", zh: "法杖", ja: "杖" },

  //element
  Flame: { en: "Flame", zh: "火", ja: "火" },
  Water: { en: "Water", zh: "水", ja: "水" },
  Wind: { en: "Wind", zh: "风", ja: "風" },
  Light: { en: "Light", zh: "光", ja: "光" },
  Shadow: { en: "Shadow", zh: "暗", ja: "闇" },
};
